(add-to-list 'load-path "~/.emacs.d/async/")
(add-to-list 'load-path "~/.emacs.d/helm/")
(require 'helm-config)
;(require 'helm)
(helm-mode 1)
(global-set-key (kbd "C-x b") 'helm-mini)
;(global-set-key (kbd "C-x C-b") 'helm-buffers-list)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(custom-set-variables
  '(helm-buffer-max-length nil)
)
